// Code generated by re2go 4.0.2, DO NOT EDIT.
package re2go

// Original pattern: (?i)byline|author|dateline|writtenby|p-author
func IsByline(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy3
			case 'B':
				fallthrough
			case 'b':
				goto yy4
			case 'D':
				fallthrough
			case 'd':
				goto yy5
			case 'P':
				fallthrough
			case 'p':
				goto yy6
			case 'W':
				fallthrough
			case 'w':
				goto yy7
			default:
				if limit <= cursor {
					goto yy29
				}
				goto yy1
			}
		yy1:
			cursor++
		yy2:
			{
				continue
			}
		yy3:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy8
			default:
				goto yy2
			}
		yy4:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy10
			default:
				goto yy2
			}
		yy5:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy11
			default:
				goto yy2
			}
		yy6:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy12
			default:
				goto yy2
			}
		yy7:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy13
			default:
				goto yy2
			}
		yy8:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy14
			default:
				goto yy9
			}
		yy9:
			cursor = marker
			goto yy2
		yy10:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy15
			default:
				goto yy9
			}
		yy11:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy16
			default:
				goto yy9
			}
		yy12:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy17
			default:
				goto yy9
			}
		yy13:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy18
			default:
				goto yy9
			}
		yy14:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy19
			default:
				goto yy9
			}
		yy15:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy20
			default:
				goto yy9
			}
		yy16:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy10
			default:
				goto yy9
			}
		yy17:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy8
			default:
				goto yy9
			}
		yy18:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy21
			default:
				goto yy9
			}
		yy19:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy22
			default:
				goto yy9
			}
		yy20:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy23
			default:
				goto yy9
			}
		yy21:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy24
			default:
				goto yy9
			}
		yy22:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy25
			default:
				goto yy9
			}
		yy23:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy25
			default:
				goto yy9
			}
		yy24:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy26
			default:
				goto yy9
			}
		yy25:
			cursor++
			{
				return true
			}
		yy26:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy27
			default:
				goto yy9
			}
		yy27:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy28
			default:
				goto yy9
			}
		yy28:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy25
			default:
				goto yy9
			}
		yy29:
			{
				return false
			}
		}

	}
}
