// Code generated by re2go 4.0.2, DO NOT EDIT.
package re2go

// Original pattern: (?i)-ad-|ai2html|banner|breadcrumbs|combx|comment|community|cover-wrap|disqus|extra|footer|gdpr|header|legends|menu|related|remark|replies|rss|shoutbox|sidebar|skyscraper|social|sponsor|supplemental|ad-break|agegate|pagination|pager|popup|yom-remote
func IsUnlikelyCandidates(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy3
			case 'A':
				fallthrough
			case 'a':
				goto yy4
			case 'B':
				fallthrough
			case 'b':
				goto yy5
			case 'C':
				fallthrough
			case 'c':
				goto yy6
			case 'D':
				fallthrough
			case 'd':
				goto yy7
			case 'E':
				fallthrough
			case 'e':
				goto yy8
			case 'F':
				fallthrough
			case 'f':
				goto yy9
			case 'G':
				fallthrough
			case 'g':
				goto yy10
			case 'H':
				fallthrough
			case 'h':
				goto yy11
			case 'L':
				fallthrough
			case 'l':
				goto yy12
			case 'M':
				fallthrough
			case 'm':
				goto yy13
			case 'P':
				fallthrough
			case 'p':
				goto yy14
			case 'R':
				fallthrough
			case 'r':
				goto yy15
			case 'S':
				fallthrough
			case 's':
				goto yy16
			case 'Y':
				fallthrough
			case 'y':
				goto yy17
			default:
				if limit <= cursor {
					goto yy141
				}
				goto yy1
			}
		yy1:
			cursor++
		yy2:
			{
				continue
			}
		yy3:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy18
			default:
				goto yy2
			}
		yy4:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy20
			case 'G':
				fallthrough
			case 'g':
				goto yy21
			case 'I':
				fallthrough
			case 'i':
				goto yy22
			default:
				goto yy2
			}
		yy5:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy23
			case 'R':
				fallthrough
			case 'r':
				goto yy24
			default:
				goto yy2
			}
		yy6:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy25
			default:
				goto yy2
			}
		yy7:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy26
			default:
				goto yy2
			}
		yy8:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'X':
				fallthrough
			case 'x':
				goto yy27
			default:
				goto yy2
			}
		yy9:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy28
			default:
				goto yy2
			}
		yy10:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy29
			default:
				goto yy2
			}
		yy11:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy30
			default:
				goto yy2
			}
		yy12:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy31
			default:
				goto yy2
			}
		yy13:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy32
			default:
				goto yy2
			}
		yy14:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy33
			case 'O':
				fallthrough
			case 'o':
				goto yy34
			default:
				goto yy2
			}
		yy15:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy35
			case 'S':
				fallthrough
			case 's':
				goto yy36
			default:
				goto yy2
			}
		yy16:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy37
			case 'I':
				fallthrough
			case 'i':
				goto yy38
			case 'K':
				fallthrough
			case 'k':
				goto yy39
			case 'O':
				fallthrough
			case 'o':
				goto yy40
			case 'P':
				fallthrough
			case 'p':
				goto yy41
			case 'U':
				fallthrough
			case 'u':
				goto yy42
			default:
				goto yy2
			}
		yy17:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy43
			default:
				goto yy2
			}
		yy18:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy44
			default:
				goto yy19
			}
		yy19:
			cursor = marker
			goto yy2
		yy20:
			cursor++
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy45
			default:
				goto yy19
			}
		yy21:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy46
			default:
				goto yy19
			}
		yy22:
			cursor++
			yych = input[cursor]
			switch yych {
			case '2':
				goto yy47
			default:
				goto yy19
			}
		yy23:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy48
			default:
				goto yy19
			}
		yy24:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy49
			default:
				goto yy19
			}
		yy25:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy50
			case 'V':
				fallthrough
			case 'v':
				goto yy51
			default:
				goto yy19
			}
		yy26:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy52
			default:
				goto yy19
			}
		yy27:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy53
			default:
				goto yy19
			}
		yy28:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy54
			default:
				goto yy19
			}
		yy29:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy55
			default:
				goto yy19
			}
		yy30:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy56
			default:
				goto yy19
			}
		yy31:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy57
			default:
				goto yy19
			}
		yy32:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy58
			default:
				goto yy19
			}
		yy33:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy59
			default:
				goto yy19
			}
		yy34:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy60
			default:
				goto yy19
			}
		yy35:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy61
			case 'M':
				fallthrough
			case 'm':
				goto yy62
			case 'P':
				fallthrough
			case 'p':
				goto yy63
			default:
				goto yy19
			}
		yy36:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy64
			default:
				goto yy19
			}
		yy37:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy65
			default:
				goto yy19
			}
		yy38:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy66
			default:
				goto yy19
			}
		yy39:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy67
			default:
				goto yy19
			}
		yy40:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy68
			default:
				goto yy19
			}
		yy41:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy69
			default:
				goto yy19
			}
		yy42:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy70
			default:
				goto yy19
			}
		yy43:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy71
			default:
				goto yy19
			}
		yy44:
			cursor++
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy64
			default:
				goto yy19
			}
		yy45:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy72
			default:
				goto yy19
			}
		yy46:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy73
			default:
				goto yy19
			}
		yy47:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy74
			default:
				goto yy19
			}
		yy48:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy75
			default:
				goto yy19
			}
		yy49:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy76
			default:
				goto yy19
			}
		yy50:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy77
			case 'M':
				fallthrough
			case 'm':
				goto yy78
			default:
				goto yy19
			}
		yy51:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy79
			default:
				goto yy19
			}
		yy52:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Q':
				fallthrough
			case 'q':
				goto yy80
			default:
				goto yy19
			}
		yy53:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy81
			default:
				goto yy19
			}
		yy54:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy75
			default:
				goto yy19
			}
		yy55:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy64
			default:
				goto yy19
			}
		yy56:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy75
			default:
				goto yy19
			}
		yy57:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy82
			default:
				goto yy19
			}
		yy58:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy64
			default:
				goto yy19
			}
		yy59:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy55
			case 'I':
				fallthrough
			case 'i':
				goto yy83
			default:
				goto yy19
			}
		yy60:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy84
			default:
				goto yy19
			}
		yy61:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy85
			default:
				goto yy19
			}
		yy62:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy86
			default:
				goto yy19
			}
		yy63:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy87
			default:
				goto yy19
			}
		yy64:
			cursor++
			{
				return true
			}
		yy65:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy88
			default:
				goto yy19
			}
		yy66:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy89
			default:
				goto yy19
			}
		yy67:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy90
			default:
				goto yy19
			}
		yy68:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy91
			default:
				goto yy19
			}
		yy69:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy92
			default:
				goto yy19
			}
		yy70:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy93
			default:
				goto yy19
			}
		yy71:
			cursor++
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy94
			default:
				goto yy19
			}
		yy72:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy95
			default:
				goto yy19
			}
		yy73:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy96
			default:
				goto yy19
			}
		yy74:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy97
			default:
				goto yy19
			}
		yy75:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy55
			default:
				goto yy19
			}
		yy76:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy98
			default:
				goto yy19
			}
		yy77:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'X':
				fallthrough
			case 'x':
				goto yy64
			default:
				goto yy19
			}
		yy78:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy99
			case 'U':
				fallthrough
			case 'u':
				goto yy100
			default:
				goto yy19
			}
		yy79:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy101
			default:
				goto yy19
			}
		yy80:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy36
			default:
				goto yy19
			}
		yy81:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy64
			default:
				goto yy19
			}
		yy82:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy102
			default:
				goto yy19
			}
		yy83:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy103
			default:
				goto yy19
			}
		yy84:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy64
			default:
				goto yy19
			}
		yy85:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy104
			default:
				goto yy19
			}
		yy86:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy105
			default:
				goto yy19
			}
		yy87:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy106
			default:
				goto yy19
			}
		yy88:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy107
			default:
				goto yy19
			}
		yy89:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy108
			default:
				goto yy19
			}
		yy90:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy109
			default:
				goto yy19
			}
		yy91:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy110
			default:
				goto yy19
			}
		yy92:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy111
			default:
				goto yy19
			}
		yy93:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy112
			default:
				goto yy19
			}
		yy94:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy113
			default:
				goto yy19
			}
		yy95:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy114
			default:
				goto yy19
			}
		yy96:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy115
			default:
				goto yy19
			}
		yy97:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy110
			default:
				goto yy19
			}
		yy98:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy116
			default:
				goto yy19
			}
		yy99:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy117
			default:
				goto yy19
			}
		yy100:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy118
			default:
				goto yy19
			}
		yy101:
			cursor++
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy119
			default:
				goto yy19
			}
		yy102:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy36
			default:
				goto yy19
			}
		yy103:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy120
			default:
				goto yy19
			}
		yy104:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy121
			default:
				goto yy19
			}
		yy105:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy64
			default:
				goto yy19
			}
		yy106:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy36
			default:
				goto yy19
			}
		yy107:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy122
			default:
				goto yy19
			}
		yy108:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy55
			default:
				goto yy19
			}
		yy109:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy123
			default:
				goto yy19
			}
		yy110:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy64
			default:
				goto yy19
			}
		yy111:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy55
			default:
				goto yy19
			}
		yy112:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy124
			default:
				goto yy19
			}
		yy113:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy125
			default:
				goto yy19
			}
		yy114:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy105
			default:
				goto yy19
			}
		yy115:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy64
			default:
				goto yy19
			}
		yy116:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy126
			default:
				goto yy19
			}
		yy117:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy64
			default:
				goto yy19
			}
		yy118:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy127
			default:
				goto yy19
			}
		yy119:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'W':
				fallthrough
			case 'w':
				goto yy128
			default:
				goto yy19
			}
		yy120:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy129
			default:
				goto yy19
			}
		yy121:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy64
			default:
				goto yy19
			}
		yy122:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy77
			default:
				goto yy19
			}
		yy123:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy130
			default:
				goto yy19
			}
		yy124:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy131
			default:
				goto yy19
			}
		yy125:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy132
			default:
				goto yy19
			}
		yy126:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy133
			default:
				goto yy19
			}
		yy127:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy134
			default:
				goto yy19
			}
		yy128:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy135
			default:
				goto yy19
			}
		yy129:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy136
			default:
				goto yy19
			}
		yy130:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy75
			default:
				goto yy19
			}
		yy131:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy137
			default:
				goto yy19
			}
		yy132:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy96
			default:
				goto yy19
			}
		yy133:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy138
			default:
				goto yy19
			}
		yy134:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy64
			default:
				goto yy19
			}
		yy135:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy84
			default:
				goto yy19
			}
		yy136:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy139
			default:
				goto yy19
			}
		yy137:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy140
			default:
				goto yy19
			}
		yy138:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy36
			default:
				goto yy19
			}
		yy139:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy64
			default:
				goto yy19
			}
		yy140:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy91
			default:
				goto yy19
			}
		yy141:
			{
				return false
			}
		}

	}
}

// Original pattern: (?i)and|article|body|column|content|main|shadow
func MaybeItsACandidate(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy145
			case 'B':
				fallthrough
			case 'b':
				goto yy146
			case 'C':
				fallthrough
			case 'c':
				goto yy147
			case 'M':
				fallthrough
			case 'm':
				goto yy148
			case 'S':
				fallthrough
			case 's':
				goto yy149
			default:
				if limit <= cursor {
					goto yy173
				}
				goto yy143
			}
		yy143:
			cursor++
		yy144:
			{
				continue
			}
		yy145:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy150
			case 'R':
				fallthrough
			case 'r':
				goto yy152
			default:
				goto yy144
			}
		yy146:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy153
			default:
				goto yy144
			}
		yy147:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy154
			default:
				goto yy144
			}
		yy148:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy155
			default:
				goto yy144
			}
		yy149:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy156
			default:
				goto yy144
			}
		yy150:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy157
			default:
				goto yy151
			}
		yy151:
			cursor = marker
			goto yy144
		yy152:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy158
			default:
				goto yy151
			}
		yy153:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy159
			default:
				goto yy151
			}
		yy154:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy160
			case 'N':
				fallthrough
			case 'n':
				goto yy161
			default:
				goto yy151
			}
		yy155:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy162
			default:
				goto yy151
			}
		yy156:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy163
			default:
				goto yy151
			}
		yy157:
			cursor++
			{
				return true
			}
		yy158:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy164
			default:
				goto yy151
			}
		yy159:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Y':
				fallthrough
			case 'y':
				goto yy157
			default:
				goto yy151
			}
		yy160:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy165
			default:
				goto yy151
			}
		yy161:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy166
			default:
				goto yy151
			}
		yy162:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy157
			default:
				goto yy151
			}
		yy163:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy167
			default:
				goto yy151
			}
		yy164:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy168
			default:
				goto yy151
			}
		yy165:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy162
			default:
				goto yy151
			}
		yy166:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy169
			default:
				goto yy151
			}
		yy167:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy170
			default:
				goto yy151
			}
		yy168:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy171
			default:
				goto yy151
			}
		yy169:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy172
			default:
				goto yy151
			}
		yy170:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'W':
				fallthrough
			case 'w':
				goto yy157
			default:
				goto yy151
			}
		yy171:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy157
			default:
				goto yy151
			}
		yy172:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy157
			default:
				goto yy151
			}
		yy173:
			{
				return false
			}
		}

	}
}

// Commas as used in Latin, Sindhi, Chinese and various other scripts.
// see: https://en.wikipedia.org/wiki/Comma#Comma_variants
// Original pattern: \u002C|\u060C|\uFE50|\uFE10|\uFE11|\u2E41|\u2E34|\u2E32|\uFF0C
func CountCommas(input string) int {
	var count int
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case ',':
				goto yy177
			case 0xD8:
				goto yy178
			case 0xE2:
				goto yy179
			case 0xEF:
				goto yy180
			default:
				if limit <= cursor {
					goto yy187
				}
				goto yy175
			}
		yy175:
			cursor++
		yy176:
			{
				continue
			}
		yy177:
			cursor++
			{
				count++
				continue
			}
		yy178:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x8C:
				goto yy177
			default:
				goto yy176
			}
		yy179:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0xB8:
				goto yy181
			case 0xB9:
				goto yy183
			default:
				goto yy176
			}
		yy180:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0xB8:
				goto yy184
			case 0xB9:
				goto yy185
			case 0xBC:
				goto yy186
			default:
				goto yy176
			}
		yy181:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0xB2:
				fallthrough
			case 0xB4:
				goto yy177
			default:
				goto yy182
			}
		yy182:
			cursor = marker
			goto yy176
		yy183:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x81:
				goto yy177
			default:
				goto yy182
			}
		yy184:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x90, 0x91:
				goto yy177
			default:
				goto yy182
			}
		yy185:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x90:
				goto yy177
			default:
				goto yy182
			}
		yy186:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x8C:
				goto yy177
			default:
				goto yy182
			}
		yy187:
			{
				return count
			}
		}

	}
}
