// Code generated by re2go 4.0.2, DO NOT EDIT.
package re2go

import "strings"

// Original pattern: (?i)\s{2,}
func NormalizeSpaces(input string) string {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	// Variable for capturing parentheses (twice the number of groups).
	const YYMAXNMATCH = 1

	yypmatch := make([]int, YYMAXNMATCH*2)
	var yynmatch int
	_ = yynmatch

	// Autogenerated tag variables used by the lexer to track tag values.
	var yyt1 int
	_ = yyt1

	var start int
	var sb strings.Builder

	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				yyt1 = cursor
				goto yy3
			default:
				if limit <= cursor {
					goto yy6
				}
				goto yy1
			}
		yy1:
			cursor++
		yy2:
			{
				continue
			}
		yy3:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy4
			default:
				goto yy2
			}
		yy4:
			cursor++
			yych = input[cursor]
			switch yych {
			case '\t', '\n':
				fallthrough
			case '\f', '\r':
				fallthrough
			case ' ':
				goto yy4
			default:
				goto yy5
			}
		yy5:
			yynmatch = 1
			yypmatch[0] = yyt1
			yypmatch[1] = cursor
			{
				sb.WriteString(input[start:yypmatch[0]])
				sb.WriteString(" ")
				start = yypmatch[1]
				continue
			}
		yy6:
			{
				sb.WriteString(input[start:limit])
				return sb.String()
			}
		}

	}
}
